# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1280, 720)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_menu = QtWidgets.QFrame(self.centralwidget)
        self.frame_menu.setMinimumSize(QtCore.QSize(600, 600))
        self.frame_menu.setMaximumSize(QtCore.QSize(600, 600))
        self.frame_menu.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-repeat: no-repeat;\n"
"background-position: center;")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.logo = QtWidgets.QFrame(self.frame_menu)
        self.logo.setGeometry(QtCore.QRect(0, 40, 601, 251))
        self.logo.setStyleSheet("background-image: url(:/assets/logo.jpeg);")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.btn_new = QtWidgets.QPushButton(self.frame_menu)
        self.btn_new.setGeometry(QtCore.QRect(190, 360, 211, 61))
        self.btn_new.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_new.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.btn_new.setAutoDefault(False)
        self.btn_new.setDefault(False)
        self.btn_new.setFlat(False)
        self.btn_new.setObjectName("btn_new")
        self.btn_read = QtWidgets.QPushButton(self.frame_menu)
        self.btn_read.setGeometry(QtCore.QRect(190, 460, 211, 61))
        self.btn_read.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_read.setStyleSheet("QPushButton {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(223, 223, 223);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(200, 200, 200);\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"}")
        self.btn_read.setAutoDefault(False)
        self.btn_read.setDefault(False)
        self.btn_read.setFlat(False)
        self.btn_read.setObjectName("btn_read")
        self.horizontalLayout.addWidget(self.frame_menu, 0, QtCore.Qt.AlignVCenter)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_new.setText(_translate("MainWindow", "Novo Projeto"))
        self.btn_read.setText(_translate("MainWindow", "Ver Projetos"))
import src_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.showMaximized()
    sys.exit(app.exec_())
